In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')
sns.set_context('talk')

In [2]:
df = pd.read_csv('List of best-selling video games.csv')
df.head()

,Rank,Title,Sales,Series,Platform(s),Initial release date,Developer(s)[a],Publisher(s)[a]
0,1.0,Minecraft,"238,000,000[b]",Minecraft,Multi-platform[c],"November 18, 2011[d]",Mojang Studios,Xbox Game Studios
1,2.0,Grand Theft Auto V,"170,000,000",Grand Theft Auto,Multi-platform,"September 17, 2013",Rockstar North,Rockstar Games
2,3.0,Tetris (EA),"100,000,000",Tetris,Multi-platform[e],"September 12, 2006",EA Mobile,Electronic Arts
3,4.0,Wii Sports,"82,900,000",Wii,Wii,"November 19, 2006",Nintendo EAD,Nintendo
4,5.0,PUBG: Battlegrounds,"75,000,000",PUBG Universe,Multi-platform,"December 20, 2017",PUBG Corporation,PUBG Corporation

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Rank                  49 non-null     float64
 1   Title                 49 non-null     object
 2   Sales                 43 non-null     object
 3   Series                49 non-null     object
 4   Platform(s)           49 non-null     object
 5   Initial release date  49 non-null     object
 6   Developer(s)[a]       49 non-null     object
 7   Publisher(s)[a]       49 non-null     object
dtypes: float64(1), object(7)
memory usage: 3.2+ KB

In [4]:
df.isna().sum()

Rank                    0
Title                   0
Sales                   6
Series                  0
Platform(s)             0
Initial release date    0
Developer(s)[a]         0
Publisher(s)[a]         0
dtype: int64

In [5]:
df[df.Sales.isna()]

,Rank,Title,Sales,Series,Platform(s),Initial release date,Developer(s)[a],Publisher(s)[a]
20,21.0,Diablo III / Reaper of Souls,NaN,Diablo,Multi-platform,16.May.12,Blizzard Entertainment,Blizzard Entertainment
21,22.0,Human: Fall Flat,NaN,None,Multi-platform,"July 22, 2016",No Brakes Games,Curve Digital
22,23.0,The Elder Scrolls V: Skyrim,NaN,The Elder Scrolls,Multi-platform,"November 11, 2011",Bethesda Game Studios,Bethesda Softworks
25,26.0,Pokémon Gold / Silver / Crystal,NaN,Pokémon,Game Boy Color,"November 21, 1999",Game Freak,Nintendo
35,36.0,Pokémon Sword / Shield,NaN,Pokémon,Nintendo Switch,"November 15, 2019",Game Freak,Nintendo / The Pokémon Company
42,43.0,Kinect Adventures!,NaN,None,Xbox 360,"November 4, 2010",Good Science Studio,Xbox Game Studios

In [6]:
df2 = pd.read_csv('popular_video_games_1980_2023.csv')
df2.head()

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
0,0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17K,3.8K,4.6K,4.8K
1,1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21K,3.2K,6.3K,3.6K
2,2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30K,2.5K,5K,2.6K
3,3,Undertale,"Sep 15, 2015","['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,28K,679,4.9K,1.8K
4,4,Hollow Knight,"Feb 24, 2017",['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",21K,2.4K,8.3K,2.3K

In [7]:
df2.describe()

        Unnamed: 0       Rating
count  1512.000000  1499.000000
mean    755.500000     3.719346
std     436.621117     0.532608
min       0.000000     0.700000
25%     377.750000     3.400000
50%     755.500000     3.800000
75%    1133.250000     4.100000
max    1511.000000     4.800000

In [8]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1512 entries, 0 to 1511
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         1512 non-null   int64
 1   Title              1512 non-null   object
 2   Release Date       1512 non-null   object
 3   Team               1511 non-null   object
 4   Rating             1499 non-null   float64
 5   Times Listed       1512 non-null   object
 6   Number of Reviews  1512 non-null   object
 7   Genres             1512 non-null   object
 8   Summary            1511 non-null   object
 9   Reviews            1512 non-null   object
 10  Plays              1512 non-null   object
 11  Playing            1512 non-null   object
 12  Backlogs           1512 non-null   object
 13  Wishlist           1512 non-null   object
dtypes: float64(1), int64(1), object(12)
memory usage: 165.5+ KB

In [9]:
df2.isna().sum()

Unnamed: 0            0
Title                 0
Release Date          0
Team                  1
Rating               13
Times Listed          0
Number of Reviews     0
Genres                0
Summary               1
Reviews               0
Plays                 0
Playing               0
Backlogs              0
Wishlist              0
dtype: int64

In [10]:
df3 = pd.read_csv('Video_games_esrb_rating.csv')
df3.head()

,title,console,alcohol_reference,animated_blood,blood,blood_and_gore,cartoon_violence,crude_humor,drug_reference,fantasy_violence,...,sexual_content,sexual_themes,simulated_gambling,strong_janguage,strong_sexual_content,suggestive_themes,use_of_alcohol,use_of_drugs_and_alcohol,violence,esrb_rating
0,Monster Jam Steel Titans 2,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,E
1,Subnautica: Below Zero,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,ET
2,NIER REPLICANT VER.1.22474487139…,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,M
3,Jamestown+,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,ET
4,Neptunia Virtual Stars,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,T

In [11]:
df4 = pd.read_csv('test_esrb.csv')
df4.head()

,title,console,alcohol_reference,animated_blood,blood,blood_and_gore,cartoon_violence,crude_humor,drug_reference,fantasy_violence,...,sexual_content,sexual_themes,simulated_gambling,strong_janguage,strong_sexual_content,suggestive_themes,use_of_alcohol,use_of_drugs_and_alcohol,violence,esrb_rating
0,Still Time,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,T
1,Surf World Series,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,E
2,The Metronomicon: Slay the Dance Floor,1,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,T
3,Windjammers,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,E
4,Rock of Ages 2: Bigger and Boulder,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,ET

In [12]:
df3.describe()

,console,alcohol_reference,animated_blood,blood,blood_and_gore,cartoon_violence,crude_humor,drug_reference,fantasy_violence,intense_violence,...,partial_nudity,sexual_content,sexual_themes,simulated_gambling,strong_janguage,strong_sexual_content,suggestive_themes,use_of_alcohol,use_of_drugs_and_alcohol,violence
count,1895.000000,1895.000000,1895.000000,1895.000000,1895.000000,1895.000000,1895.000000,1895.000000,1895.000000,1895.000000,...,1895.000000,1895.000000,1895.000000,1895.000000,1895.000000,1895.000000,1895.000000,1895.000000,1895.000000,1895.000000
mean,0.475462,0.050132,0.010026,0.227968,0.126121,0.019525,0.054354,0.034828,0.220580,0.118206,...,0.013193,0.034301,0.057520,0.067018,0.118206,0.035884,0.117678,0.015831,0.015831,0.063852
std,0.499529,0.218275,0.099655,0.419633,0.332074,0.138398,0.226774,0.183394,0.414748,0.322937,...,0.114129,0.182049,0.232895,0.250120,0.322937,0.186050,0.322312,0.124855,0.124855,0.244554
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [13]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1895 entries, 0 to 1894
Data columns (total 34 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     1895 non-null   object
 1   console                   1895 non-null   int64
 2   alcohol_reference         1895 non-null   int64
 3   animated_blood            1895 non-null   int64
 4   blood                     1895 non-null   int64
 5   blood_and_gore            1895 non-null   int64
 6   cartoon_violence          1895 non-null   int64
 7   crude_humor               1895 non-null   int64
 8   drug_reference            1895 non-null   int64
 9   fantasy_violence          1895 non-null   int64
 10  intense_violence          1895 non-null   int64
 11  language                  1895 non-null   int64
 12  lyrics                    1895 non-null   int64
 13  mature_humor              1895 non-null   int64
 14  mild_blood                1895 non-null   int64
 15  mild_cartoon_violence     1895 non-null   int64
 16  mild_fantasy_violence     1895 non-null   int64
 17  mild_language             1895 non-null   int64
 18  mild_lyrics               1895 non-null   int64
 19  mild_suggestive_themes    1895 non-null   int64
 20  mild_violence             1895 non-null   int64
 21  no_descriptors            1895 non-null   int64
 22  nudity                    1895 non-null   int64
 23  partial_nudity            1895 non-null   int64
 24  sexual_content            1895 non-null   int64
 25  sexual_themes             1895 non-null   int64
 26  simulated_gambling        1895 non-null   int64
 27  strong_janguage           1895 non-null   int64
 28  strong_sexual_content     1895 non-null   int64
 29  suggestive_themes         1895 non-null   int64
 30  use_of_alcohol            1895 non-null   int64
 31  use_of_drugs_and_alcohol  1895 non-null   int64
 32  violence                  1895 non-null   int64
 33  esrb_rating               1895 non-null   object
dtypes: int64(32), object(2)
memory usage: 503.5+ KB

In [14]:
df3.isna().sum()

title                       0
console                     0
alcohol_reference           0
animated_blood              0
blood                       0
blood_and_gore              0
cartoon_violence            0
crude_humor                 0
drug_reference              0
fantasy_violence            0
intense_violence            0
language                    0
lyrics                      0
mature_humor                0
mild_blood                  0
mild_cartoon_violence       0
mild_fantasy_violence       0
mild_language               0
mild_lyrics                 0
mild_suggestive_themes      0
mild_violence               0
no_descriptors              0
nudity                      0
partial_nudity              0
sexual_content              0
sexual_themes               0
simulated_gambling          0
strong_janguage             0
strong_sexual_content       0
suggestive_themes           0
use_of_alcohol              0
use_of_drugs_and_alcohol    0
violence                    0
esrb_rating                 0
dtype: int64

In [15]:
df5 = pd.read_json('hltb.jsonlines', lines=True)
df5.head()

,Name,Stats,steam_app_id,Release_date,Genres,Review_score
0,Borderlands 3,{'Additional Content': {'Moxxi's Heist of the ...,397540.0,2019-09-13,"First-Person, Action, Shooter",76
1,Dying Light,{'Additional Content': {'The Following': {'Pol...,239140.0,2015-01-27,"Action, Adventure, Open World, Survival Horror",78
2,Middle-Earth: Shadow of War,{'Additional Content': {'Blade of Galadriel': ...,356190.0,2017-10-10,"Action, Adventure",76
3,Counter-Strike: Global Offensive,"{'Multi-Player': {'Co-Op': {'Polled': '34', 'A...",730.0,2012-08-21,"First-Person, Shooter",74
4,Grand Theft Auto IV,{'Additional Content': {'The Lost and Damned':...,5152.0,2008-04-29,"Third-Person, Action, Sandbox, Shooter",82

In [16]:
df5.Name.unique()

array(['Borderlands 3', 'Dying Light', 'Middle-Earth: Shadow of War', ...,
       "Apocalypse: Party's Over", '10mg :)', 'Sinistar'], dtype=object)

In [17]:
for dataframe in [df,df2,df3,df4,df5]:
    print(len(dataframe), dataframe.columns)

49 Index(['Rank', 'Title', 'Sales', 'Series', 'Platform(s)',
       'Initial release date', 'Developer(s)[a]', 'Publisher(s)[a]'],
      dtype='object')
1512 Index(['Unnamed: 0', 'Title', 'Release Date', 'Team', 'Rating', 'Times Listed',
       'Number of Reviews', 'Genres', 'Summary', 'Reviews', 'Plays', 'Playing',
       'Backlogs', 'Wishlist'],
      dtype='object')
1895 Index(['title', 'console', 'alcohol_reference', 'animated_blood', 'blood',
       'blood_and_gore', 'cartoon_violence', 'crude_humor', 'drug_reference',
       'fantasy_violence', 'intense_violence', 'language', 'lyrics',
       'mature_humor', 'mild_blood', 'mild_cartoon_violence',
       'mild_fantasy_violence', 'mild_language', 'mild_lyrics',
       'mild_suggestive_themes', 'mild_violence', 'no_descriptors', 'nudity',
       'partial_nudity', 'sexual_content', 'sexual_themes',
       'simulated_gambling', 'strong_janguage', 'strong_sexual_content',
       'suggestive_themes', 'use_of_alcohol', 'use_of_drugs_and_alcohol',
       'violence', 'esrb_rating'],
      dtype='object')
500 Index(['title', 'console', 'alcohol_reference', 'animated_blood', 'blood',
       'blood_and_gore', 'cartoon_violence', 'crude_humor', 'drug_reference',
       'fantasy_violence', 'intense_violence', 'language', 'lyrics',
       'mature_humor', 'mild_blood', 'mild_cartoon_violence',
       'mild_fantasy_violence', 'mild_language', 'mild_lyrics',
       'mild_suggestive_themes', 'mild_violence', 'no_descriptors', 'nudity',
       'partial_nudity', 'sexual_content', 'sexual_themes',
       'simulated_gambling', 'strong_janguage', 'strong_sexual_content',
       'suggestive_themes', 'use_of_alcohol', 'use_of_drugs_and_alcohol',
       'violence', 'esrb_rating'],
      dtype='object')
60409 Index(['Name', 'Stats', 'steam_app_id', 'Release_date', 'Genres',
       'Review_score'],
      dtype='object')

In [18]:
in_df = []
in_df2 = []
in_df3 = []
in_df4 = []
in_df5 = []
df_lowered = df.Title.str.lower()
df2_lowered = df2.Title.str.lower()
df3_lowered = df3.title.str.lower()
df4_lowered = df4.title.str.lower()
df5_lowered = df5.Name.str.lower().unique()
for game in df5_lowered:
    if game in df_lowered.values:
        in_df.append(1)
    else:
        in_df.append(0)
    
    if game in df2_lowered.values:
        in_df2.append(1)
    else:
        in_df2.append(0)
    
    if game in df3_lowered.values:
        in_df3.append(1)
    else:
        in_df3.append(0)
    
    if game in df4_lowered.values:
        in_df4.append(1)
    else:
        in_df4.append(0)
    
    in_df5.append(1)

In [19]:
sum(in_df)

36

In [20]:
sum(in_df2)

956

In [21]:
sum(in_df3)

1265

In [22]:
sum(in_df4)

337

In [23]:
sum(in_df5)

59700

In [24]:
dictionary = {'name':df5_lowered, 'bestselling': in_df, 'popular': in_df2, 'esrb_rating':in_df3, 'esrb_test':in_df4, 'playtimes':in_df5}
overlap_df = pd.DataFrame(dictionary)
overlap_df.head()

,name,bestselling,popular,esrb_rating,esrb_test,playtimes
0,borderlands 3,0,1,1,0,1
1,dying light,0,0,0,0,1
2,middle-earth: shadow of war,0,0,0,1,1
3,counter-strike: global offensive,0,0,0,0,1
4,grand theft auto iv,1,1,0,0,1

In [25]:
len(overlap_df[(overlap_df.popular == 0) & (overlap_df.esrb_test == 1)])

310

In [26]:
df[~df.Title.str.lower().isin(overlap_df.name)]

,Rank,Title,Sales,Series,Platform(s),Initial release date,Developer(s)[a],Publisher(s)[a]
2,3.0,Tetris (EA),"100,000,000",Tetris,Multi-platform[e],"September 12, 2006",EA Mobile,Electronic Arts
4,5.0,PUBG: Battlegrounds,"75,000,000",PUBG Universe,Multi-platform,"December 20, 2017",PUBG Corporation,PUBG Corporation
6,7.0,Mario Kart 8 / Deluxe,"56,870,000",Mario Kart,Wii U / Switch,29.May.14,Nintendo EAD,Nintendo
7,8.0,Pokémon Red / Green / Blue / Yellow,"47,520,000",Pokémon,Game Boy / Color,"February 27, 1996",Game Freak,Nintendo
10,11.0,Wii Fit / Plus,"43,800,000",Wii,Wii,"December 1, 2007",Nintendo EAD,Nintendo
11,12.0,Tetris (1989)[j],"43,000,000",Tetris,Game Boy / NES,"June 14, 1989",Nintendo R&D1,Nintendo
14,15.0,The Witcher 3 / Hearts of Stone / Blood and Wine,"40,000,000",The Witcher,Multi-platform,19.May.15,CD Projekt Red,CD Projekt
20,21.0,Diablo III / Reaper of Souls,NaN,Diablo,Multi-platform,16.May.12,Blizzard Entertainment,Blizzard Entertainment
25,26.0,Pokémon Gold / Silver / Crystal,NaN,Pokémon,Game Boy Color,"November 21, 1999",Game Freak,Nintendo
34,35.0,Pokémon Sun / Moon / Ultra Sun / Ultra Moon,"25,370,000",Pokémon,Nintendo 3DS,"November 18, 2016",Game Freak,Nintendo / The Pokémon Company
35,36.0,Pokémon Sword / Shield,NaN,Pokémon,Nintendo Switch,"November 15, 2019",Game Freak,Nintendo / The Pokémon Company
37,38.0,Pokémon Diamond / Pearl / Platinum,"24,730,000",Pokémon,Nintendo DS,"September 28, 2006",Game Freak,Nintendo / The Pokémon Company
42,43.0,Kinect Adventures!,NaN,None,Xbox 360,"November 4, 2010",Good Science Studio,Xbox Game Studios

In [27]:
df2[~df2.Title.str.lower().isin(overlap_df.name)][:50]

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
25,25,God of War Ragnarök,"Nov 09, 2022","['Sony Interactive Entertainment', 'SIE Santa ...",4.4,1.7K,1.7K,"['Adventure', 'Brawler']",God of War: Ragnarök is the ninth installment ...,"['Amazang !', 'Deep storytelling, intense game...",5.3K,801,2K,3.3K
28,28,Disco Elysium: The Final Cut,"May 01, 2020",['ZA/UM'],4.6,1.1K,1.1K,"['Adventure', 'Indie', 'RPG']",Disco Elysium: The Final Cut is a groundbreaki...,"[""a captivating journey from start to finish. ...",6K,1.2K,5K,2.7K
31,31,NieR Replicant ver.1.22474487139...,"Apr 22, 2021","['Toylogic', 'Square Enix']",4.2,1.5K,1.5K,"['Adventure', 'RPG']",NieR Replicant ver.1.22474487139... is an upda...,"['Not as good as automata but still slaps', 'T...",6.7K,880,4.1K,3.7K
87,87,Persona 3 FES,"Apr 19, 2007","['Atlus', 'Atlus USA']",4.1,1.4K,1.4K,"['RPG', 'Simulator', 'Visual Novel']",Shin Megami Tensei: Persona 3 FES is an add-on...,"[""I had heard a lot of things about Persona 3'...",8.4K,584,2.9K,1.5K
91,91,Pokémon Violet,"Nov 18, 2022","['Game Freak', 'Nintendo']",3.5,753,753,"['Adventure', 'RPG', 'Turn Based Strategy']","The Pokémon Scarlet and Pokémon Violet games, ...","[""It's quite difficult for me to gather my tho...",3.4K,868,747,750
95,95,Metroid Prime Remastered,"Feb 08, 2023","['Nintendo', 'Retro Studios']",4.5,372,372,"['Adventure', 'Platform', 'Shooter']",Get behind the visor of intergalactic bounty h...,"[""That Nintendo just announced this and droppe...",1.1K,593,1.1K,1.4K
101,101,Xenoblade Chronicles: Definitive Edition,"May 29, 2020","['Monolith Soft', 'Nintendo']",4.3,1.4K,1.4K,['RPG'],Discover the origins of Shulk as he and his co...,"['i wish british people were real', 'That’s Du...",7.4K,849,3.6K,1.9K
118,118,Chrome Dino,"Sep 01, 2014",['Google'],3.5,124,124,['Arcade'],Chrome Dino is a game easter egg in Google's C...,"[""Get this shit off my screen I'm trying to br...",14K,122,197,35
140,140,Guilty Gear: Strive,"Jun 11, 2021","['Bandai Namco Studios', 'Arc System Works']",3.9,810,810,['Fighting'],Discover the Smell of the Game with Guilty Gea...,['the song is called smell of the game because...,5.5K,713,805,1.2K
155,155,Pokémon Emerald,"Sep 16, 2004","['Nintendo', 'Game Freak']",4.0,1.2K,1.2K,"['Adventure', 'RPG', 'Turn Based Strategy']",Pokémon Emerald Version is a sister game to Po...,['Is my most replayed pokemon with SoulSilver'...,16K,219,1K,376
158,158,Pokémon Scarlet,"Nov 18, 2022","['Nintendo', 'Game Freak']",3.5,596,596,"['Adventure', 'RPG', 'Turn Based Strategy']","The Pokémon Scarlet and Pokémon Violet games, ...","[""This is a game I can see why people like it,...",2.6K,580,489,496
193,193,Pokémon Black,"Sep 18, 2010","['Nintendo', 'Game Freak']",4.0,1K,1K,"['Adventure', 'RPG', 'Turn Based Strategy']",Pokémon Black Version and Pokémon White Versio...,['desptie being\n \n ...,12K,186,1.1K,461
214,214,Yakuza 3 Remastered,"Aug 09, 2018",['Ryū Ga Gotoku Studios'],3.3,755,755,"['Adventure', 'RPG', 'Simulator']","This is the third Yakuza game, remastered for ...","['茶番だ', 'rikiya didnt deserve this', 'i pirate...",4.3K,235,2.3K,904
221,221,The House in Fata Morgana,"Dec 27, 2012","['Dramatic Create', 'NOVECT']",4.4,544,544,"['Adventure', 'Indie', 'Visual Novel']",A gothic suspense tale set in a cursed mansion...,"['Peak fiction? More like mid fiction', ""not U...",1.7K,250,1.5K,1.3K
226,226,Final Fantasy XIV Online,"Aug 27, 2013",['Square Enix'],3.7,643,643,"['Adventure', 'RPG', 'Strategy']",Take part in an epic and ever-changing Final F...,"[""sometimes it feels like a big ask to tell pe...",5.9K,1.1K,818,363
234,234,Pokémon Sword,"Nov 15, 2019","['Game Freak', 'Nintendo']",2.9,837,837,"['Adventure', 'RPG']",Unsheathe your sword and take up your shield!\...,"[""It was alright lol, my first mainline pokemo...",9.7K,301,924,500
245,245,Pokémon White,"Sep 18, 2010","['Nintendo', 'Game Freak']",4.1,814,814,"['Adventure', 'RPG', 'Turn Based Strategy']",Pokémon White Version and Pokémon Black Versio...,"['Unova has the best Pokémon designs, honestly...",9K,115,705,270
252,252,Umineko: When They Cry Chiru,"Sep 15, 2009",['07th Expansion'],4.6,324,324,"['Adventure', 'Visual Novel']",Umineko no Naku Koro ni Chiru is the second ha...,"['cried like a little bitch ngl', ""God I reall...",1.7K,108,582,493
256,256,Persona 4,"Jul 10, 2008","['Atlus', 'NIS America']",4.0,815,815,"['RPG', 'Simulator', 'Visual Novel']",An entry in the JRPG/visual novel hybrid Perso...,"['I played Persona 4 after P5, and my love for...",5.7K,158,1K,599
277,277,Ōkami HD,"Oct 30, 2012","['Clover Studio', 'Capcom']",4.2,527,527,"['Adventure', 'RPG']",Experience the critically acclaimed masterpiec...,"['very beatiful and interesting as a whole', '...",3.3K,321,3.1K,1.2K
280,280,Pokémon Black Version 2,"Jun 23, 2012","['Game Freak', 'Nintendo']",4.2,776,776,"['Adventure', 'RPG', 'Turn Based Strategy']",Pokémon Black Version 2 and Pokémon White Vers...,"[""It is the best one... music, fights, story, ...",7.6K,130,1.1K,449
283,283,Hollow Knight: Voidheart Edition,"Sep 25, 2018",['Team Cherry'],4.5,462,462,"['Adventure', 'Indie', 'Platform']","""Explore twisting caverns, ancient cities and ...",['Hollow knight simplesmente é maravilhoso e p...,3.9K,295,1.3K,363
296,296,The Legend of Zelda: Twilight Princess,"Nov 19, 2006","['Nintendo', 'Nintendo EAD Software Developmen...",4.1,642,642,"['Adventure', 'RPG']",The Legend of Zelda: Twilight Princess was ini...,"[""No es el Zelda más perfecto ni de lejos, de ...",6K,82,1.1K,466
309,309,Fire Emblem: The Blazing Blade,"Apr 25, 2003","['Intelligent Systems Co., Ltd.', 'Nintendo']",3.7,609,609,"['RPG', 'Strategy', 'Tactical']",It is the seventh game of the Fire Emblem seri...,"[""Fire Emblem is like pizza. Like... even a ba...",3.9K,158,1.2K,401
312,312,Pokémon Moon,"Nov 18, 2016","['The Pokémon Company', 'Game Freak']",3.3,648,648,"['Adventure', 'RPG', 'Strategy', 'Turn Based S...",Pokémon Sun and Pokémon Moon trademarks were r...,"[""pokemon's honestly been going downhill since...",7.9K,75,653,234
313,313,Zelda II: The Adventure of Link,"Jan 14, 1987","['Nintendo', 'Nintendo EAD']",2.6,756,756,"['Adventure', 'RPG']",Zelda II: The Adventure of Link is the second ...,['Another massive adventure that is often look...,4.5K,55,1.1K,290
314,314,Battlefield 4,"Oct 29, 2013","['EA Digital Illusions CE', 'Electronic Arts']",3.5,431,431,['Shooter'],Battlefield 4 is the genre-defining action blo...,['This is a clear example of less is sometimes...,7.1K,72,506,124
351,351,God of War Ragnarök,"Nov 09, 2022","['Sony Interactive Entertainment', 'SIE Santa ...",4.4,1.7K,1.7K,"['Adventure', 'Brawler']",God of War: Ragnarök is the ninth installment ...,"['Amazang !', 'Deep storytelling, intense game...",5.3K,801,2K,3.3K
354,354,Disco Elysium: The Final Cut,"May 01, 2020",['ZA/UM'],4.6,1.1K,1.1K,"['Adventure', 'Indie', 'RPG']",Disco Elysium: The Final Cut is a groundbreaki...,"[""a captivating journey from start to finish. ...",6K,1.2K,5K,2.7K
357,357,NieR Replicant ver.1.22474487139...,"Apr 22, 2021","['Toylogic', 'Square Enix']",4.2,1.5K,1.5K,"['Adventure', 'RPG']",NieR Replicant ver.1.22474487139... is an upda...,"['Not as good as automata but still slaps', 'T...",6.7K,880,4.1K,3.7K
398,398,Chrome Dino,"Sep 01, 2014",['Google'],3.5,124,124,['Arcade'],Chrome Dino is a game easter egg in Google's C...,"[""Get this shit off my screen I'm trying to br...",14K,122,197,35
429,429,Guilty Gear: Strive,"Jun 11, 2021","['Bandai Namco Studios', 'Arc System Works']",3.9,810,810,['Fighting'],Discover the Smell of the Game with Guilty Gea...,['the song is called smell of the game because...,5.5K,713,805,1.2K
444,444,Pokémon Emerald,"Sep 16, 2004","['Nintendo', 'Game Freak']",4.0,1.2K,1.2K,"['Adventure', 'RPG', 'Turn Based Strategy']",Pokémon Emerald Version is a sister game to Po...,['Is my most replayed pokemon with SoulSilver'...,16K,219,1K,376
447,447,Pokémon Scarlet,"Nov 18, 2022","['Nintendo', 'Game Freak']",3.5,596,596,"['Adventure', 'RPG', 'Turn Based Strategy']","The Pokémon Scarlet and Pokémon Violet games, ...","[""This is a game I can see why people like it,...",2.6K,580,489,496
460,460,Pokémon Black,"Sep 18, 2010","['Nintendo', 'Game Freak']",4.0,1K,1K,"['Adventure', 'RPG', 'Turn Based Strategy']",Pokémon Black Version and Pokémon White Versio...,['desptie being\n \n ...,12K,186,1.1K,461
481,481,Yakuza 3 Remastered,"Aug 09, 2018",['Ryū Ga Gotoku Studios'],3.3,755,755,"['Adventure', 'RPG', 'Simulator']","This is the third Yakuza game, remastered for ...","['茶番だ', 'rikiya didnt deserve this', 'i pirate...",4.3K,235,2.3K,904
488,488,The House in Fata Morgana,"Dec 27, 2012","['Dramatic Create', 'NOVECT']",4.4,544,544,"['Adventure', 'Indie', 'Visual Novel']",A gothic suspense tale set in a cursed mansion...,"['Peak fiction? More like mid fiction', ""not U...",1.7K,250,1.5K,1.3K
493,493,Final Fantasy XIV Online,"Aug 27, 2013",['Square Enix'],3.7,643,643,"['Adventure', 'RPG', 'Strategy']",Take part in an epic and ever-changing Final F...,"[""sometimes it feels like a big ask to tell pe...",5.9K,1.1K,818,363
501,501,Pokémon Sword,"Nov 15, 2019","['Game Freak', 'Nintendo']",2.9,837,837,"['Adventure', 'RPG']",Unsheathe your sword and take up your shield!\...,"[""It was alright lol, my first mainline pokemo...",9.7K,301,924,500
532,532,Pokémon White,"Sep 18, 2010","['Nintendo', 'Game Freak']",4.1,814,814,"['Adventure', 'RPG', 'Turn Based Strategy']",Pokémon White Version and Pokémon Black Versio...,"['Unova has the best Pokémon designs, honestly...",9K,115,705,270
539,539,Umineko: When They Cry Chiru,"Sep 15, 2009",['07th Expansion'],4.6,324,324,"['Adventure', 'Visual Novel']",Umineko no Naku Koro ni Chiru is the second ha...,"['cried like a little bitch ngl', ""God I reall...",1.7K,108,582,493
543,543,Persona 4,"Jul 10, 2008","['Atlus', 'NIS America']",4.0,815,815,"['RPG', 'Simulator', 'Visual Novel']",An entry in the JRPG/visual novel hybrid Perso...,"['I played Persona 4 after P5, and my love for...",5.7K,158,1K,599
564,564,Ōkami HD,"Oct 30, 2012","['Clover Studio', 'Capcom']",4.2,527,527,"['Adventure', 'RPG']",Experience the critically acclaimed masterpiec...,"['very beatiful and interesting as a whole', '...",3.3K,321,3.1K,1.2K
567,567,Pokémon Black Version 2,"Jun 23, 2012","['Game Freak', 'Nintendo']",4.2,776,776,"['Adventure', 'RPG', 'Turn Based Strategy']",Pokémon Black Version 2 and Pokémon White Vers...,"[""It is the best one... music, fights, story, ...",7.6K,130,1.1K,449
570,570,Hollow Knight: Voidheart Edition,"Sep 25, 2018",['Team Cherry'],4.5,462,462,"['Adventure', 'Indie', 'Platform']","""Explore twisting caverns, ancient cities and ...",['Hollow knight simplesmente é maravilhoso e p...,3.9K,295,1.3K,363
580,580,The Walking Dead: Season Two,"Dec 17, 2013","['Telltale Games', 'Skybound Games']",3.5,559,559,"['Adventure', 'Point-and-Click', 'Puzzle']","Similar to the previous season, The Walking De...","['bastante más lento, llama la atención alguna...",6.7K,35,718,262
588,588,Pokémon Sun,"Nov 18, 2016","['The Pokémon Company', 'Game Freak']",3.3,600,600,"['Adventure', 'RPG', 'Strategy', 'Turn Based S...",Pokémon Sun and Pokémon Moon trademarks were r...,"[""Favorite Pokemon game of all time for the so...",7.6K,74,596,230
596,596,Shovel Knight: Treasure Trove,"Dec 09, 2019","['Yacht Club Games', 'Nintendo']",4.3,445,445,"['Adventure', 'Indie', 'Platform']",Shovel Knight: Treasure Trove is the full and ...,"[""SHOVEL KNIGHT AAAHHH FUCKING LOVE SHOVEL KNI...",3.8K,186,1.3K,574
597,597,Ghost of Tsushima: Director's Cut,"Aug 20, 2021","['Sony Interactive Entertainment', 'Sucker Pun...",4.2,345,345,"['Adventure', 'RPG']",Ghost of Tsushima: Director's Cut Includes:\n ...,['my name is jin sakai i owe yo sista my life'...,1.8K,257,993,621
599,599,Street Fighter III: 3rd Strike,"May 12, 1999","['Capcom', 'Virgin Interactive Entertainment']",4.2,763,763,"['Arcade', 'Fighting']",Street Fighter III 3rd Strike: Fight for the F...,"['Akuma everytime', 'Ganhei meu computador nov...",3.7K,71,281,202

In [28]:
df3[~df3.title.str.lower().isin(overlap_df.name)][:50]

,title,console,alcohol_reference,animated_blood,blood,blood_and_gore,cartoon_violence,crude_humor,drug_reference,fantasy_violence,...,sexual_content,sexual_themes,simulated_gambling,strong_janguage,strong_sexual_content,suggestive_themes,use_of_alcohol,use_of_drugs_and_alcohol,violence,esrb_rating
2,NIER REPLICANT VER.1.22474487139…,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,M
3,Jamestown+,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,ET
9,FATAL FURY™ BATTLE ARCHIVES VOL.2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,T
10,NBA LIVE 20,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,E
14,Fallout 76: Steel Dawn,1,0,0,0,1,0,0,1,0,...,0,0,0,1,0,1,0,0,0,M
16,Override 2: Super Mech League – Ultraman Delux...,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,T
17,Turrican Flashback,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,ET
25,Bibi & Tina at the Horse Farm,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,E
28,Five Nights at Freddy's: Core Collection,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,T
30,EA SPORTS™ FIFA 21 ÉDITION NXT LVL,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,E
31,EA SPORTS™ FIFA 21 NXT LEVEL EDITION,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,E
32,EA SPORTS™ MADDEN NFL 21 ÉDITION NXT LVL,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,E
33,EA SPORTS™ MADDEN NFL 21 NXT LEVEL EDITION,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,E
34,My Universe - Pet Clinic Cats and Dogs,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,E
38,METAL SLUG ANTHOLOGY™,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,T
39,NHL 94 Rewind,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,E
45,Bubble Bobble 4 Friends: The Baron is Back!,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,E
47,Fortnite - The Last Laugh Bundle,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,T
51,Les Sims™ 4 Escapade enneigée,1,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,T
52,Need for Speed Hot Pursuit Remastered,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,ET
53,The Sims™ 4 Snowy Escape,1,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,T
54,Professor Rubik's Brain Fitness,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,E
56,My Universe - Cooking Star Restaurant,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,E
60,PAW Patrol Mighty Pups Save Adventure Bay,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,E
61,Watch Dogs Complete Edition,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,M
62,Planet Coaster Console Edition,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,E
63,THE KING OF FIGHTERS™ COLLECTION: THE OROCHI SAGA,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,1,0,0,1,T
65,Art of Fighting Anthology,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,T
68,Space Channel 5 VR Kinda Funky News Flash!,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,ET
76,MY UNIVERSE - FASHION BOUTIQUE,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,E
77,The Walking Dead: Saints & Sinners - Complete ...,0,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,M
80,Train Sim World®2: Collector's Edition,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,E
84,TRANSFORMERS:BATTLEGROUNDS,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,ET
92,NHL 21 Great Eight Edition,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,ET
93,Fishing Sim World: Bass Pro Shops Edition,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,E
105,Hotline Miami 2: Wrong Number,0,0,0,0,1,0,0,0,0,...,0,1,1,1,0,0,0,0,0,M
110,Freedom Finger,0,0,0,1,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,M
112,The Dark Pictures Anthology: Little Hope,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,M
114,Black Desert Prestige Edition,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,T
123,Goosebumps Dead of Night,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,ET
124,Port Royale 4,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,ET
125,My Universe : School teacher,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,E
126,"Sakuna: Of Rice and Ruin ""Divine Edition""",0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,T
132,Human Fall Flat,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,E
133,Power Rangers: Battle for the Grid - Collector...,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,T
136,Tin and Kuna,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,E
137,Les Sims™ 4 Star Wars™: Voyage sur Batuu,1,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,T
138,Los Sims™ 4 Star Wars™: Viaje a Batuu,1,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,T
139,The Sims™ 4 Star Wars™: Journey to Batuu,1,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,T
141,Call of Duty®: Black Ops Cold War,1,0,0,0,1,0,0,1,0,...,0,0,0,1,0,1,0,0,0,M

In [29]:
overlap_df[overlap_df.name.str.contains('pokémon')]

,name,bestselling,popular,esrb_rating,esrb_test,playtimes
55,pokémon scarlet and violet,0,0,0,0,1
141,pokémon legends: arceus,0,1,0,0,1
245,pokémon sword and shield,0,0,0,0,1
694,"pokémon: let's go, pikachu! and let's go, eevee!",0,0,0,0,1
751,pokémon x and y,0,0,0,0,1
...,...,...,...,...,...,...
26285,my pokémon ranch,0,0,0,0,1
30453,pokémon light platinum,0,0,0,0,1
33051,pokémon smile,0,0,0,0,1
33336,pokémon rumble rush,0,0,0,0,1
36507,pokémon box: ruby & sapphire,0,0,0,0,1

In [30]:
df3[df3.title.str.contains('etris')]

,title,console,alcohol_reference,animated_blood,blood,blood_and_gore,cartoon_violence,crude_humor,drug_reference,fantasy_violence,...,sexual_content,sexual_themes,simulated_gambling,strong_janguage,strong_sexual_content,suggestive_themes,use_of_alcohol,use_of_drugs_and_alcohol,violence,esrb_rating
89,Puyo Puyo Tetris 2,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,ET
790,Tetris Effect,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,E

In [31]:
df5['single_player'] = df5.Stats.map(lambda x: x.get('Single-Player'))
df5.loc[df5.single_player.notna(), 'main_story'] = df5[df5.single_player.notna()].single_player.map(lambda x: x.get('Main Story'))
df5.loc[df5.main_story.notna(), 'main_average'] = df5[df5.main_story.notna()].main_story.map(lambda x: x.get('Average'))
df5.loc[df5.single_player.notna(), 'all_playstyles'] = df5[df5.single_player.notna()].single_player.map(lambda x: x.get('All PlayStyles'))
df5.loc[df5.all_playstyles.notna(), 'all_styles_average'] = df5[df5.all_playstyles.notna()].all_playstyles.map(lambda x: x.get('Average'))
df5.loc[df5.single_player.notna(), 'completionist'] = df5[df5.single_player.notna()].single_player.map(lambda x: x.get('Completionist'))
df5.loc[df5.completionist.notna(), 'completionist_average'] = df5[df5.completionist.notna()].completionist.map(lambda x: x.get('Average'))

df5['multi_player'] = df5.Stats.map(lambda x: x.get('Multi-Player'))
df5.loc[df5.multi_player.notna(), 'co_op'] = df5[df5.multi_player.notna()].multi_player.map(lambda x: x.get('Co-Op'))
df5.loc[df5.co_op.notna(), 'co_op_average'] = df5[df5.co_op.notna()].co_op.map(lambda x: x.get('Average'))
df5.loc[df5.multi_player.notna(), 'competitive'] = df5[df5.multi_player.notna()].multi_player.map(lambda x: x.get('Competitive'))
df5.loc[df5.competitive.notna(), 'competitive_average'] = df5[df5.competitive.notna()].competitive.map(lambda x: x.get('Average'))

In [32]:
df5.loc[df5.competitive.notna(), 'competitive_average'] = df5[df5.competitive.notna()].competitive.map(lambda x: x.get('Average'))

In [33]:
df5 = df5.drop(['single_player', 'main_story', 'all_playstyles', 'completionist', 'multi_player', 'co_op', 'competitive'], axis=1)

In [34]:
df5.head()

,Name,Stats,steam_app_id,Release_date,Genres,Review_score,main_average,all_styles_average,completionist_average,co_op_average,competitive_average
0,Borderlands 3,{'Additional Content': {'Moxxi's Heist of the ...,397540.0,2019-09-13,"First-Person, Action, Shooter",76,23h 17m,43h 24m,77h 27m,43½ Hours,19½ Hours
1,Dying Light,{'Additional Content': {'The Following': {'Pol...,239140.0,2015-01-27,"Action, Adventure, Open World, Survival Horror",78,18h 10m,32h 9m,58h 34m,31 Hours,99 Hours
2,Middle-Earth: Shadow of War,{'Additional Content': {'Blade of Galadriel': ...,356190.0,2017-10-10,"Action, Adventure",76,20h 47m,38h 30m,56h 30m,NaN,NaN
3,Counter-Strike: Global Offensive,"{'Multi-Player': {'Co-Op': {'Polled': '34', 'A...",730.0,2012-08-21,"First-Person, Shooter",74,NaN,NaN,NaN,436 Hours,884 Hours
4,Grand Theft Auto IV,{'Additional Content': {'The Lost and Damned':...,5152.0,2008-04-29,"Third-Person, Action, Sandbox, Shooter",82,27h 37m,37h 48m,77h 4m,120 Hours,25½ Hours

In [35]:
#df5['timedelta'] = pd.to_timedelta(df5.main_average)

In [36]:
df2.Reviews[0]

'["The first playthrough of elden ring is one of the best eperiences gaming can offer you but after youve explored everything in the open world and you\'ve experienced all of the surprises you lose motivation to go exploring on repeat playthroughs which takes a lot away from the replayability which is a very important thing for from games imo.", \'a replay solidified my love for elden ring. so easily my favorite game of all time. actually beating malenia this time was also an amazing feeling. i just love being in this world man its the greatest of all time\', \'The game is absolutely beautiful, with so much to do. The replayability is crazy. And it never gets old with it too.\', \'Took everything great about the Soulsborne games and make it 100% better.\', \'I play with my overlevelled friend every time and we still fail sometimes (he’s on NG6), insanely difficult game lol\\n                     \\n                     gorgeous graphics, animations, everything about this game is so beautiful. deserves all the hype it gets. If you have a powerful enough pc I definitely recommend you play it on there, if you use keyboard, you’ll want to change the keybinds because the defaults are ass.\', "Tied as my favorite souls game with Bloodborne, truly one I\'ll keep coming back too."]'

In [37]:
working_data = df2.merge(df5, how='inner', left_on='Title', right_on='Name')

In [38]:
working_data.head()

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres_x,Summary,Reviews,...,Stats,steam_app_id,Release_date,Genres_y,Review_score,main_average,all_styles_average,completionist_average,co_op_average,competitive_average
0,0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",...,{'Single-Player': {'Main Story': {'Polled': '5...,1245620.0,2022-02-25,"Third-Person, Action, Open World, Role-Playing",93,54h 18m,110h 19m,137h 14m,31 Hours,52½ Hours
1,326,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",...,{'Single-Player': {'Main Story': {'Polled': '5...,1245620.0,2022-02-25,"Third-Person, Action, Open World, Role-Playing",93,54h 18m,110h 19m,137h 14m,31 Hours,52½ Hours
2,776,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""By far one of the most disappointing game I'...",...,{'Single-Player': {'Main Story': {'Polled': '5...,1245620.0,2022-02-25,"Third-Person, Action, Open World, Role-Playing",93,54h 18m,110h 19m,137h 14m,31 Hours,52½ Hours
3,1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,...,{'Single-Player': {'Main Story': {'Polled': '1...,1145360.0,2020-09-17,"Action, Roguelike, Role-Playing",90,23h 18m,46h 8m,97h 25m,NaN,NaN
4,327,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,...,{'Single-Player': {'Main Story': {'Polled': '1...,1145360.0,2020-09-17,"Action, Roguelike, Role-Playing",90,23h 18m,46h 8m,97h 25m,NaN,NaN

In [39]:
working_data.columns

Index(['Unnamed: 0', 'Title', 'Release Date', 'Team', 'Rating', 'Times Listed',
       'Number of Reviews', 'Genres_x', 'Summary', 'Reviews', 'Plays',
       'Playing', 'Backlogs', 'Wishlist', 'Name', 'Stats', 'steam_app_id',
       'Release_date', 'Genres_y', 'Review_score', 'main_average',
       'all_styles_average', 'completionist_average', 'co_op_average',
       'competitive_average'],
      dtype='object')

In [40]:
len(working_data)

1385

In [41]:
working_data.isna().sum()

Unnamed: 0                  0
Title                       0
Release Date                0
Team                        1
Rating                     10
Times Listed                0
Number of Reviews           0
Genres_x                    0
Summary                     1
Reviews                     0
Plays                       0
Playing                     0
Backlogs                    0
Wishlist                    0
Name                        0
Stats                       0
steam_app_id              609
Release_date                0
Genres_y                    0
Review_score                0
main_average               69
all_styles_average         64
completionist_average      90
co_op_average            1128
competitive_average      1128
dtype: int64

In [42]:
len(working_data.Title.unique())

929

In [43]:
len(df2)

1512

In [44]:
len(df2.Title.unique())

1099

In [45]:
dupes = working_data[working_data.Title.duplicated(keep=False)]

In [47]:
dupes.sort_values('Title')

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres_x,Summary,Reviews,...,Stats,steam_app_id,Release_date,Genres_y,Review_score,main_average,all_styles_average,completionist_average,co_op_average,competitive_average
451,969,A Plague Tale: Innocence,"May 14, 2019","['Focus Entertainment', 'Asobo Studio']",3.7,852,852,"['Adventure', 'RPG']","A Plague Tale: Innocence, on PlayStation 4, Xb...",['Antes da review vale ressaltar que peguei o ...,...,{'Single-Player': {'Main Story': {'Polled': '1...,752590.0,2019-05-14,"Action, Adventure, Stealth",80,10h 53m,12h 22m,16h 11m,NaN,NaN
450,454,A Plague Tale: Innocence,"May 14, 2019","['Focus Entertainment', 'Asobo Studio']",3.7,852,852,"['Adventure', 'RPG']","A Plague Tale: Innocence, on PlayStation 4, Xb...",['Antes da review vale ressaltar que peguei o ...,...,{'Single-Player': {'Main Story': {'Polled': '1...,752590.0,2019-05-14,"Action, Adventure, Stealth",80,10h 53m,12h 22m,16h 11m,NaN,NaN
449,187,A Plague Tale: Innocence,"May 14, 2019","['Focus Entertainment', 'Asobo Studio']",3.7,852,852,"['Adventure', 'RPG']","A Plague Tale: Innocence, on PlayStation 4, Xb...",['Antes da review vale ressaltar que peguei o ...,...,{'Single-Player': {'Main Story': {'Polled': '1...,752590.0,2019-05-14,"Action, Adventure, Stealth",80,10h 53m,12h 22m,16h 11m,NaN,NaN
892,769,Agar.io,"Apr 28, 2015","['Miniclip.com', 'Matheus Valadares']",2.2,81,81,"['Indie', 'Strategy']",Agar.io is a Massively-multiplayer top-down st...,"['""A Ganância que te move... É a mesma que te ...",...,"{'Platform': {'PC': {'Polled': '2', 'Main': '1...",NaN,2015-04-28,"Action, Strategy",56,NaN,NaN,NaN,NaN,NaN
893,1270,Agar.io,"Apr 28, 2015","['Miniclip.com', 'Matheus Valadares']",2.2,81,81,"['Indie', 'Strategy']",Agar.io is a Massively-multiplayer top-down st...,"['""A Ganância que te move... É a mesma que te ...",...,"{'Platform': {'PC': {'Polled': '2', 'Main': '1...",NaN,2015-04-28,"Action, Strategy",56,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,393,Yakuza Kiwami,"Jan 21, 2016","['Sega', 'Ryū Ga Gotoku Studios']",3.7,1.2K,1.2K,"['Adventure', 'Brawler', 'RPG']",Yakuza Kiwami is a remake of the 2005 open wor...,"[""This game is a really good game in it's own ...",...,{'Single-Player': {'Main Story': {'Polled': '6...,834530.0,2016-01-21,"Third-Person, Action, Adventure",80,18h 3m,31h 36m,82h 53m,NaN,NaN
270,859,Yakuza Kiwami,"Jan 21, 2016","['Sega', 'Ryū Ga Gotoku Studios']",3.7,1.2K,1.2K,"['Adventure', 'Brawler', 'RPG']",Yakuza Kiwami is a remake of the 2005 open wor...,['Conseguiram pegar na mesma engine do 0 e tor...,...,{'Single-Player': {'Main Story': {'Polled': '6...,834530.0,2016-01-21,"Third-Person, Action, Adventure",80,18h 3m,31h 36m,82h 53m,NaN,NaN
268,113,Yakuza Kiwami,"Jan 21, 2016","['Sega', 'Ryū Ga Gotoku Studios']",3.7,1.2K,1.2K,"['Adventure', 'Brawler', 'RPG']",Yakuza Kiwami is a remake of the 2005 open wor...,"[""This game is a really good game in it's own ...",...,{'Single-Player': {'Main Story': {'Polled': '6...,834530.0,2016-01-21,"Third-Person, Action, Adventure",80,18h 3m,31h 36m,82h 53m,NaN,NaN
567,508,Yume Nikki,"Jun 26, 2004","['Kikiyama', 'DeNA Co., Ltd.']",4.0,770,770,"['Adventure', 'Indie']",Yume Nikki is a 32-Bit freeware game created b...,"['such an unique experience i love it', 'yume ...",...,{'Single-Player': {'Main Story': {'Polled': '5...,650700.0,2004-00-00,Role-Playing,78,5h 14m,5h 48m,7h 30m,NaN,NaN
566,241,Yume Nikki,"Jun 26, 2004","['Kikiyama', 'DeNA Co., Ltd.']",4.0,770,770,"['Adventure', 'Indie']",Yume Nikki is a 32-Bit freeware game created b...,"['such an unique experience i love it', 'yume ...",...,{'Single-Player': {'Main Story': {'Polled': '5...,650700.0,2004-00-00,Role-Playing,78,5h 14m,5h 48m,7h 30m,NaN,NaN

In [48]:
df2[df2.Title == 'Elden Ring']

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
0,0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17K,3.8K,4.6K,4.8K
326,326,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17K,3.8K,4.6K,4.8K
776,776,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""By far one of the most disappointing game I'...",17K,3.8K,4.6K,4.8K

In [49]:
dupes[dupes.Title == 'Elden Ring']

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres_x,Summary,Reviews,...,Stats,steam_app_id,Release_date,Genres_y,Review_score,main_average,all_styles_average,completionist_average,co_op_average,competitive_average
0,0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",...,{'Single-Player': {'Main Story': {'Polled': '5...,1245620.0,2022-02-25,"Third-Person, Action, Open World, Role-Playing",93,54h 18m,110h 19m,137h 14m,31 Hours,52½ Hours
1,326,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",...,{'Single-Player': {'Main Story': {'Polled': '5...,1245620.0,2022-02-25,"Third-Person, Action, Open World, Role-Playing",93,54h 18m,110h 19m,137h 14m,31 Hours,52½ Hours
2,776,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""By far one of the most disappointing game I'...",...,{'Single-Player': {'Main Story': {'Polled': '5...,1245620.0,2022-02-25,"Third-Person, Action, Open World, Role-Playing",93,54h 18m,110h 19m,137h 14m,31 Hours,52½ Hours

In [50]:
working_data = working_data.drop(['Reviews'], axis=1)

In [51]:
len(working_data)

1385

In [52]:
working_data = working_data[~working_data.Title.duplicated()]

In [53]:
len(working_data)

929

In [54]:
working_data.Stats[0]

{'Single-Player': {'Main Story': {'Polled': '527',
   'Average': '54h 18m',
   'Median': '55h',
   'Rushed': '33h 48m',
   'Leisure': '82h 51m'},
  'Main + Extras': {'Polled': '2.5K',
   'Average': '102h 51m',
   'Median': '95h 58m',
   'Rushed': '64h 12m',
   'Leisure': '234h 12m'},
  'Completionist': {'Polled': '1.8K',
   'Average': '137h 14m',
   'Median': '129h',
   'Rushed': '92h 49m',
   'Leisure': '274h 3m'},
  'All PlayStyles': {'Polled': '4.8K',
   'Average': '110h 19m',
   'Median': '102h 59m',
   'Rushed': '59h 48m',
   'Leisure': '260h 49m'}},
 'Speedruns': {'Any%': {'Polled': '6',
   'Average': '3h 31m 42s',
   'Median': '2h 6m 54s',
   'Fastest': '1h 36m 58s',
   'Slowest': '8h 30m 5s'}},
 'Multi-Player': {'Co-Op': {'Polled': '19',
   'Average': '31 Hours',
   'Median': '26 Hours',
   'Least': '14½ Hours',
   'Most': '78 Hours'},
  'Competitive': {'Polled': '16',
   'Average': '52½ Hours',
   'Median': '22½ Hours',
   'Least': '19 Hours',
   'Most': '119 Hours'}},
 'Platform': {'PC': {'Polled': '2.7K',
   'Main': '52h 43m',
   'Main +': '99h 41m',
   '100%': '137h 44m',
   'Fastest': '12h 57m',
   'Slowest': '415h'},
  'PlayStation 4': {'Polled': '346',
   'Main': '56h 38m',
   'Main +': '111h 15m',
   '100%': '138h 18m',
   'Fastest': '14h 12m',
   'Slowest': '374h'},
  'PlayStation 5': {'Polled': '1.4K',
   'Main': '56h 35m',
   'Main +': '104h 7m',
   '100%': '134h 45m',
   'Fastest': '16h',
   'Slowest': '388h'},
  'Xbox One': {'Polled': '33',
   'Main': '60h 34m',
   'Main +': '124h 8m',
   '100%': '126h 57m',
   'Fastest': '41h 13m',
   'Slowest': '231h 36m'},
  'Xbox Series X/S': {'Polled': '362',
   'Main': '56h 15m',
   'Main +': '109h 20m',
   '100%': '144h 27m',
   'Fastest': '15h 34m',
   'Slowest': '391h 4m'}}}

In [58]:
working_data.loc[working_data.Stats.notna(), 'Platforms'] = list(working_data[working_data.Stats.notna()].Stats.map(lambda x: x['Platform'].keys()))

In [59]:
working_data.head()

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres_x,Summary,Plays,...,steam_app_id,Release_date,Genres_y,Review_score,main_average,all_styles_average,completionist_average,co_op_average,competitive_average,Platforms
0,0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...",17K,...,1245620.0,2022-02-25,"Third-Person, Action, Open World, Role-Playing",93,54h 18m,110h 19m,137h 14m,31 Hours,52½ Hours,"(PC, PlayStation 4, PlayStation 5, Xbox One, X..."
3,1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,21K,...,1145360.0,2020-09-17,"Action, Roguelike, Role-Playing",90,23h 18m,46h 8m,97h 25m,NaN,NaN,"(Nintendo Switch, PC, PlayStation 4, PlayStati..."
6,2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,30K,...,NaN,2017-03-03,"Third-Person, Action, Adventure, Open World",94,50h 27m,99h 2m,194h 4m,NaN,NaN,"(Emulated, Nintendo Switch, Wii U)"
9,3,Undertale,"Sep 15, 2015","['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",28K,...,391540.0,2015-09-15,"Turn-Based, Role-Playing",86,6h 59m,10h 54m,21h 29m,NaN,NaN,"(Emulated, Nintendo Switch, PC, PlayStation 4,..."
12,4,Hollow Knight,"Feb 24, 2017",['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,21K,...,367520.0,2017-02-24,"Action, Adventure",91,27h 58m,43h 9m,65h 8m,NaN,NaN,"(Emulated, Nintendo Switch, PC, PlayStation 4,..."